### ISSUE TITLE
Status of twiml-haskell vs twilio-haskell

### ISSUE THREAD

**Issue by DaveCTurner** [markandrus/twiml-haskell#6]
Hi Mark,

Could you clarify the difference in status between this project and https://github.com/markandrus/twilio-haskell - in particular, we note that this one hasn't had any commits in a couple of years and doesn't compile on GHC ≥ 8.0 (although see https://github.com/DaveCTurner/twiml-haskell/tree/lts-8-18 for a handful of patches that fix that).

Is https://github.com/markandrus/twilio-haskell where all the action is in terms of your usage, for instance? Would you recommend we prefer that for our project?

Many thanks!

**Comment by markandrus** [comment]
Hi @DaveCTurner,

Thanks for writing!

* The goal of the twilio-haskell library is to provide access to the REST API, much like Twilio's official helper libraries (twilio-node, twilio-python, etc.).
* The goal of the twiml-haskell library is provide functions for building up correct-by-construction TwiML (there are some nesting rules I wanted to see if I could encode in the type system).

I split these responsibilities across two libraries, although I could see arguments for combining them (this is what all the official helper libraries do, for example). Both of these are primarily pet projects of mine, although I am happy to accept PRs (and I put in some time on the weekends now and again).

> in particular, we note that this one hasn't had any commits in a couple of years and doesn't compile on GHC ≥ 8.0 (although see https://github.com/DaveCTurner/twiml-haskell/tree/lts-8-18 for a handful of patches that fix that).

Excellent! I'll take a look. The twilio-haskell library got some love recently ensuring we can build in more scenarios... I should see about porting that and pulling in your changes.

> Is https://github.com/markandrus/twilio-haskell where all the action is in terms of your usage, for instance? Would you recommend we prefer that for our project?

twilio-haskell is where more development has happened recently. If you need to generate TwiML, you may want to depend on this library. Alternatively, you may want to generate the TwiML yourself—I've gotten some feedback that the types in this library make it a bit difficult to use. I think it really depends on what you need to do, but I expect the twilio-haskell library will generally be more useful (since it does more things). There is, however, still some functionality missing there (for example, pagination is included, but no functions for fetching the next or previous pages).

Best,
Mark

**Comment by markandrus** [comment]
@DaveCTurner thanks for sharing your commits. I took a look at then when landing https://github.com/markandrus/twiml-haskell/pull/7. twiml-haskell 0.2.0.1 is now released with support for newer GHCs.
